spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sb_intergration
    username: root
    password: 123456


mybatis:
  type-aliases-package: com.fantsey.intersys.bean
  mapper-locations: classpath:com/fantsey/intersys/mapping/*.xml

server:
  port: 8081
  servlet:
    context-path: /test


